const TOKEN_THRESHOLDS = {
  ONE_SHOT: 60000,
  BATCH: 200000
};

const PROMPT_MAX_CHARS = 8000;

const CONTEXT_LIMITS = {
  MAX_INPUT_TOKENS: 120000,
  SAFETY_MARGIN: 0.85,
  MAX_KEYFILE_CHARS: 15000,
  MAX_TREE_CHARS: 8000,
  MAX_OTHER_DOCS_CHARS: 10000
};

const PROJECT_LIMITS = {
  MAX_FILES_PER_PROJECT: 200,
  MAX_PROJECT_TOKENS: 500000
};

const STATE_FILES = {
  LAST_SCAN: '.last-scan.json',
  INIT_STATE: '.init-state.json',
  TASK_HISTORY: '.task-history.jsonl'
};

const AI_CLIENT = {
  DEFAULT_TIMEOUT: 180000,
  MAX_RETRIES: 3,
  RETRYABLE_ERRORS: ['ETIMEDOUT', 'ECONNRESET', 'ECONNREFUSED', 'EPIPE', 'ENOTFOUND'],
  RETRYABLE_STATUS_CODES: [408, 429, 500, 502, 503, 504],
  BASE_RETRY_DELAY: 2000
};

module.exports = { TOKEN_THRESHOLDS, PROMPT_MAX_CHARS, CONTEXT_LIMITS, PROJECT_LIMITS, STATE_FILES, AI_CLIENT };
