const TOKEN_THRESHOLDS = {
  ONE_SHOT: 60000,
  BATCH: 200000
};

const PROMPT_MAX_CHARS = 8000;

const STATE_FILES = {
  LAST_SCAN: '.last-scan.json',
  INIT_STATE: '.init-state.json',
  TASK_HISTORY: '.task-history.jsonl'
};

const AI_CLIENT = {
  DEFAULT_TIMEOUT: 180000,
  MAX_RETRIES: 3,
  RETRYABLE_ERRORS: ['ETIMEDOUT', 'ECONNRESET', 'ECONNREFUSED', 'EPIPE', 'ENOTFOUND'],
  RETRYABLE_STATUS_CODES: [408, 429, 500, 502, 503, 504],
  BASE_RETRY_DELAY: 2000
};

module.exports = { TOKEN_THRESHOLDS, PROMPT_MAX_CHARS, STATE_FILES, AI_CLIENT };
