const TOKEN_THRESHOLDS = {
  ONE_SHOT: 10000,
  BATCH: 40000
};

const PROMPT_MAX_CHARS = 8000;

const CONTEXT_LIMITS = {
  MAX_INPUT_TOKENS: 120000,
  SAFETY_MARGIN: 0.85,
  MAX_KEYFILE_CHARS: 15000,
  MAX_SOURCE_FILE_CHARS: 4000,
  MAX_TREE_CHARS: 8000,
  MAX_OTHER_DOCS_CHARS: 10000
};

const PROJECT_LIMITS = {
  MAX_FILES_PER_PROJECT: 200,
  MAX_PROJECT_TOKENS: 500000,
  MAX_SCAN_BYTES: 16 * 1024 * 1024,
  MAX_SAMPLE_BYTES_PER_FILE: 64 * 1024,
  MAX_SCAN_TIME_MS: 30000,
  IO_CONCURRENCY: 8
};

const UPDATE_LIMITS = {
  MAX_EVIDENCE_CHARS: 30000,
  MAX_EVIDENCE_CHUNK_CHARS: 8000,
  MAX_FILE_EVIDENCE_CHARS: 8000
};

const STATE_FILES = {
  LAST_SCAN: '.last-scan.json',
  UPDATE_STATE: '.update-state.json',
  INIT_STATE: '.init-state.json',
  PROJECT_MANIFEST: 'project-manifest.json',
  TASK_HISTORY: '.task-history.jsonl'
};

const AI_CLIENT = {
  DEFAULT_TIMEOUT: 180000,
  DEFAULT_DEADLINE: 300000,
  MAX_RETRIES: 3,
  RETRYABLE_ERRORS: ['ETIMEDOUT', 'ECONNRESET', 'ECONNREFUSED', 'EPIPE', 'ENOTFOUND'],
  RETRYABLE_STATUS_CODES: [408, 429, 500, 502, 503, 504],
  BASE_RETRY_DELAY: 2000
};

module.exports = {
  TOKEN_THRESHOLDS,
  PROMPT_MAX_CHARS,
  CONTEXT_LIMITS,
  PROJECT_LIMITS,
  UPDATE_LIMITS,
  STATE_FILES,
  AI_CLIENT
};
